version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                name: Run tests with JUnit as reporter
                command: ./node_modules/.bin/jest --ci --runInBand --reporters=default --reporters=jest-junit --collectCoverage
                environment:
                  JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
            - store_test_results:
                path: reports
            - store_artifacts:
                path: coverage
workflows:
  build-and-test:
    jobs:
      - build-and-test
deployment:
  stage:
    branch: development
    commands:
      - scp -r locall_backend/*